name: Deploy

on:
    push:
        branches: ["**"]

jobs:
    exercise_job:
        runs-on: "ubuntu-latest"
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: dotnet setup
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.x.x'
            - run: dotnet build ConsoleAppForTestingLesson
            - run: dotnet test ConsoleAppForTestingLesson   